---
title: "fire-occurrence"
author: "Helen Evangelina"
date: "23/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(dplyr)
library(leaflet)
library(readr)
library(KernSmooth)
library(shinyWidgets)
library(plotly)
library(sp)
library(mapview)
library(leafem)
library(rgdal)
library(maptools)
library(raster)
library(DT)
library(htmlwidgets)
library(lubridate)
library(forcats)
```



```{r}
training <- read.csv("data/training.csv")

predict <- read.csv("data/predict_x.csv")

predict <- dplyr::select(predict, -FOR_CODE)
  
predict <- mutate(predict,
                     year = factor(year(time)),
                     month = factor(month(time), levels = c(10,11,12,1,2,3,4,5,6,7,8,9)),
                     day = factor(day(time), levels = c(1:31)),
                     wod = factor(wday(time), levels = c(1:7)))

predict <- mutate(predict,
                     log_dist_cfa = log(dist_cfa),
                     log_dist_camp = log(dist_camp),
                     log_dist_road = log(dist_road),
                     COVER = factor(COVER),
                     HEIGHT = factor(HEIGHT))

predict <- predict %>%
  dplyr::select(-time, -id, -dist_cfa, - dist_camp, -dist_road) 
  
```

```{r}
training <- training %>%
    filter(!CAUSE %in% c("BURNING BUILDING",
                         "WASTE DISPOSAL, INDUSTRIAL, SAWMILL, TIP",
                         "WASTE DISPOSAL, DOMESTIC",
                         "BURNING VEHICLE, MACHINE",
                         "BURNING BUILDING")) %>%
    filter(new_cause != "other") %>%
    filter(new_cause != "relight")
  
  
  training <- dplyr::select(training, -c(EVENTID:FIRE_NUM), -id, -CAUSE, -FOR_CODE)
  
  training <- mutate(training,
                     year = factor(year(FIRE_START)),
                     month = factor(month(FIRE_START), levels = c(10,11,12,1,2,3)),
                     day = factor(day(FIRE_START), levels = c(1:31)),
                     wod = factor(wday(FIRE_START), levels = c(1:7)))
  
  training <- filter(training, month %in% c(10,11,12,1,2,3))
  
  training <- na.omit(training)
  
  training <- mutate(training, new_cause = ifelse(new_cause == "accidental_human", "accident", new_cause)) %>%
    mutate(new_cause = ifelse(new_cause == "burning_off_human", "burning_off", new_cause)) %>%
    mutate(new_cause = factor(new_cause)) %>%
    mutate(FOR_TYPE = factor(FOR_TYPE))
  
#  training <- na.omit(training)
  
  training <- mutate(training,
                     log_dist_cfa = log(dist_cfa),
                     log_dist_camp = log(dist_camp),
                     log_dist_road = log(dist_road),
                     COVER = factor(COVER),
                     HEIGHT = factor(HEIGHT))
  
  training <- rename(training, cause = new_cause)
  training <- mutate(training,
                     cause = fct_relevel(cause,
                                         "lightning",
                                         "accident",
                                         "arson",
                                         "burning_off"))
  
  training <- na.omit(training)
  
  training <- dplyr::select(training, -dist_road, -dist_cfa, -dist_camp, -FIRE_START, -cause)
```

```{r}
joined_data <- rbind(training, predict)
```

```{r}
lat_lon <- joined_data %>%
  dplyr::select(lat, lon, year)
```


```{r}
yearly_data <- joined_data %>% 
  group_by(year) %>%
  summarise(count = n())
```

```{r}
coordinates(lat_lon) = c("lon", "lat")

```


```{r}
library(sf)
library(sp)
library(rnaturalearth)
au_map <- ne_states(country = 'Australia', returnclass = 'sf')
vic_map <- au_map[7,]
```

```{r}
vic_map %>%
  ggplot() +
  geom_sf()
```

```{r}
vic_raster <- raster(
  nrows = 50,
  ncols = 50,
  
  xmn = 140.9617,
  xmx = 149.9763,
  ymn = -39.13396,
  ymx = -33.99605,
  
  crs = "+proj=longlat +datum=WGS84",
  
  vals = seq(from = 1, to = 2500000, by = 1000)
  
)
```

```{r}
raster::values(vic_raster) <- stats::runif(raster::ncell(vic_raster))

vic_map_sp <- as(vic_map, Class = "Spatial")
```

```{r}
vic_raster_crop <- vic_raster %>% 
  raster::mask(mask = vic_map_sp)

vic_raster_crop
```

```{r}
plot(vic_raster_crop)
```

# with the data
```{r}
# set up projection parameter for use throughout script
projection <- "+proj=longlat +datum=WGS84"

# set up extent parameter 
ext <- extent(141, 150, -39, -34)

x <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x[] <- 0

# get cell numbers of ratser object 
tab <- table(cellFromXY(x, lat_lon))

tab

x[as.numeric(names(tab))] <- tab

#fire_data <- rasterize(joined_data[, c('lon', 'lat')], x, joined_data[, c('arf360')])

#fire_projected <- projectRaster(fire_data, crs = projection)

#fire_extended <- extend(fire_projected, ext, value = NA)

plot(x)
points(lat_lon, pch = 20)
```

```{r}
df <- data.frame(coordinates(x), count = x[])
df
```


## 2000

```{r}
lat_lon_2000 <- joined_data %>%
  filter(year == "2000")
```

```{r}
coordinates(lat_lon_2000) = c("lon", "lat")
```

```{r}
# set up projection parameter for use throughout script
projection <- "+proj=longlat +datum=WGS84"

# set up extent parameter 
ext <- extent(141, 150, -39, -34)

x1 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x1[] <- 0

tab1 <- table(cellFromXY(x1, lat_lon_2000))
tab1

x1[as.numeric(names(tab))] <- tab1

#fire_data <- rasterize(joined_data[, c('lon', 'lat')], x, joined_data[, c('arf360')])

#fire_projected <- projectRaster(fire_data, crs = projection)

#fire_extended <- extend(fire_projected, ext, value = NA)

plot(x1)
points(lat_lon_2000, pch = 20)
```

```{r}
df1 <- data.frame(coordinates(x1), count = x1[])
df1 <- df1 %>% 
  mutate(prop2000 = count/239)  %>%
  dplyr::select(-count)
```

## 2001

```{r}
lat_lon_2001 <- joined_data %>%
  filter(year == "2001")
```

```{r}
coordinates(lat_lon_2001) = c("lon", "lat")
```

```{r}
x2 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x2[] <- 0

tab2 <- table(cellFromXY(x2, lat_lon_2001))

x2[as.numeric(names(tab2))] <- tab2

plot(x2)
points(lat_lon_2001, pch = 20)
```

```{r}
df2 <- data.frame(coordinates(x2), count = x2[])
df2 <- df2 %>% 
  mutate(prop2001 = count/427)  %>%
  dplyr::select(-count)
```

## 2002

```{r}
lat_lon_2002 <- joined_data %>%
  filter(year == "2002")
```

```{r}
coordinates(lat_lon_2002) = c("lon", "lat")
```

```{r}
x3 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x3[] <- 0

tab3 <- table(cellFromXY(x3, lat_lon_2002))

x3[as.numeric(names(tab3))] <- tab3

plot(x3)
points(lat_lon_2002, pch = 20)
```

```{r}
yearly_data
```


```{r}
df3 <- data.frame(coordinates(x3), count = x3[])
df3 <- df3 %>% 
  mutate(prop2002 = count/471)  %>%
  dplyr::select(-count)
df3
```

## 2003

```{r}
lat_lon_2003 <- joined_data %>%
  filter(year == "2003")
```

```{r}
coordinates(lat_lon_2003) = c("lon", "lat")
```

```{r}
x4 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x4[] <- 0

tab4 <- table(cellFromXY(x4, lat_lon_2002))

x4[as.numeric(names(tab4))] <- tab4

plot(x4)
points(lat_lon_2003, pch = 20)
```

```{r}
yearly_data
```


```{r}
df4 <- data.frame(coordinates(x4), count = x4[])
df4 <- df4 %>% 
  mutate(prop2003 = count/426)  %>%
  dplyr::select(-count)
```

## 2004

```{r}
lat_lon_2004 <- joined_data %>%
  filter(year == "2004")
```

```{r}
coordinates(lat_lon_2004) = c("lon", "lat")
```

```{r}
x5 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x5[] <- 0

tab5 <- table(cellFromXY(x5, lat_lon_2004))
tab5

x5[as.numeric(names(tab5))] <- tab5

plot(x5)
points(lat_lon_2004, pch = 20)
```

```{r}
yearly_data
```


```{r}
df5 <- data.frame(coordinates(x5), count = x5[])
df5 <- df5 %>% 
  mutate(prop2004 = count/319) %>%
  dplyr::select(-count)
```

## 2005
```{r}
lat_lon_2005 <- joined_data %>%
  filter(year == "2005")
```

```{r}
coordinates(lat_lon_2005) = c("lon", "lat")
```

```{r}
x6 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x6[] <- 0

tab6 <- table(cellFromXY(x6, lat_lon_2005))

x6[as.numeric(names(tab6))] <- tab6

plot(x6)
points(lat_lon_2005, pch = 20)
```

```{r}
yearly_data
```


```{r}
df6 <- data.frame(coordinates(x6), count = x6[])
df6 <- df6 %>% 
  mutate(prop2005 = count/435)  %>%
  dplyr::select(-count)
```

## 2006
```{r}
lat_lon_2006 <- joined_data %>%
  filter(year == "2006")
```

```{r}
coordinates(lat_lon_2006) = c("lon", "lat")
```

```{r}
x7 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x7[] <- 0

tab7 <- table(cellFromXY(x7, lat_lon_2006))

x7[as.numeric(names(tab7))] <- tab7
```

```{r}
yearly_data
```


```{r}
df7 <- data.frame(coordinates(x7), count = x7[])
df7 <- df7 %>% 
  mutate(prop2006 = count/674)  %>%
  dplyr::select(-count)
```

## 2007
```{r}
lat_lon_2007 <- joined_data %>%
  filter(year == "2007")
```

```{r}
coordinates(lat_lon_2007) = c("lon", "lat")
```

```{r}
x8 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x8[] <- 0

tab8 <- table(cellFromXY(x8, lat_lon_2007))

x8[as.numeric(names(tab8))] <- tab8
```

```{r}
yearly_data
```


```{r}
df8 <- data.frame(coordinates(x8), count = x8[])
df8 <- df8 %>% 
  mutate(prop2007 = count/455)  %>%
  dplyr::select(-count)
df8
```

## 2008
```{r}
lat_lon_2008 <- joined_data %>%
  filter(year == "2008")
```

```{r}
coordinates(lat_lon_2008) = c("lon", "lat")
```

```{r}
x9 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x9[] <- 0

tab9 <- table(cellFromXY(x9, lat_lon_2008))

x9[as.numeric(names(tab9))] <- tab9
```

```{r}
yearly_data
```


```{r}
df9 <- data.frame(coordinates(x9), count = x9[])
df9 <- df9 %>% 
  mutate(prop2008 = count/377)  %>%
  dplyr::select(-count)
```

## 2009
```{r}
lat_lon_2009 <- joined_data %>%
  filter(year == "2009")

coordinates(lat_lon_2009) = c("lon", "lat")

x10 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x10[] <- 0

tab10 <- table(cellFromXY(x10, lat_lon_2009))

x10[as.numeric(names(tab10))] <- tab10

yearly_data
```


```{r}
df10 <- data.frame(coordinates(x10), count = x10[])
df10 <- df10 %>% 
  mutate(prop2009 = count/486)  %>%
  dplyr::select(-count)
```

## 2010
```{r}
lat_lon_2010 <- joined_data %>%
  filter(year == "2010")

coordinates(lat_lon_2010) = c("lon", "lat")

x11 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x11[] <- 0

tab11 <- table(cellFromXY(x11, lat_lon_2010))

x11[as.numeric(names(tab11))] <- tab11

yearly_data
```


```{r}
df11 <- data.frame(coordinates(x11), count = x11[])
df11 <- df11 %>% 
  mutate(prop2010 = count/219)  %>%
  dplyr::select(-count)
```

## 2011
```{r}
lat_lon_2011 <- joined_data %>%
  filter(year == "2011")

coordinates(lat_lon_2011) = c("lon", "lat")

x12 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x12[] <- 0

tab12 <- table(cellFromXY(x12, lat_lon_2011))

x12[as.numeric(names(tab12))] <- tab12

yearly_data
```


```{r}
df12 <- data.frame(coordinates(x12), count = x12[])
df12 <- df12 %>% 
  mutate(prop2011 = count/69)  %>%
  dplyr::select(-count)
```

## 2012
```{r}
lat_lon_2012 <- joined_data %>%
  filter(year == "2012")

coordinates(lat_lon_2012) = c("lon", "lat")

x13 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x13[] <- 0

tab13 <- table(cellFromXY(x13, lat_lon_2012))

x13[as.numeric(names(tab13))] <- tab13

yearly_data
```


```{r}
df13 <- data.frame(coordinates(x13), count = x13[])
df13 <- df13 %>% 
  mutate(prop2012 = count/298)  %>%
  dplyr::select(-count)
```

## 2013
```{r}
lat_lon_2013 <- joined_data %>%
  filter(year == "2013")

coordinates(lat_lon_2013) = c("lon", "lat")

x14 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x14[] <- 0

tab14 <- table(cellFromXY(x14, lat_lon_2013))

x14[as.numeric(names(tab14))] <- tab14

yearly_data
```


```{r}
df14 <- data.frame(coordinates(x14), count = x14[])
df14 <- df14 %>% 
  mutate(prop2013 = count/453)  %>%
  dplyr::select(-count)
```

## 2014
```{r}
lat_lon_2014 <- joined_data %>%
  filter(year == "2014")

coordinates(lat_lon_2014) = c("lon", "lat")

x15 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x15[] <- 0

tab15 <- table(cellFromXY(x15, lat_lon_2014))

x15[as.numeric(names(tab15))] <- tab15

yearly_data
```


```{r}
df15 <- data.frame(coordinates(x15), count = x15[])
df15 <- df15 %>% 
  mutate(prop2014 = count/743)  %>%
  dplyr::select(-count)
```

## 2015
```{r}
lat_lon_2015 <- joined_data %>%
  filter(year == "2015")

coordinates(lat_lon_2015) = c("lon", "lat")

x16 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x16[] <- 0

tab16 <- table(cellFromXY(x16, lat_lon_2015))

x16[as.numeric(names(tab16))] <- tab16

yearly_data
```


```{r}
df16 <- data.frame(coordinates(x16), count = x16[])
df16 <- df16 %>% 
  mutate(prop2015 = count/783)  %>%
  dplyr::select(-count)
```

## 2016
```{r}
lat_lon_2016 <- joined_data %>%
  filter(year == "2016")

coordinates(lat_lon_2016) = c("lon", "lat")

x17 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x17[] <- 0

tab17 <- table(cellFromXY(x17, lat_lon_2016))

x17[as.numeric(names(tab17))] <- tab17

yearly_data
```


```{r}
df17 <- data.frame(coordinates(x17), count = x17[])
df17 <- df17 %>% 
  mutate(prop2016 = count/610)  %>%
  dplyr::select(-count)
```

## 2017
```{r}
lat_lon_2017 <- joined_data %>%
  filter(year == "2017")

coordinates(lat_lon_2017) = c("lon", "lat")

x18 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x18[] <- 0

tab18 <- table(cellFromXY(x18, lat_lon_2017))

x18[as.numeric(names(tab18))] <- tab18

yearly_data
```


```{r}
df18 <- data.frame(coordinates(x18), count = x18[])
df18 <- df18 %>% 
  mutate(prop2017 = count/810) %>%
  dplyr::select(-count)
```

## 2018
```{r}
lat_lon_2018 <- joined_data %>%
  filter(year == "2018")

coordinates(lat_lon_2018) = c("lon", "lat")

x19 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x19[] <- 0

tab19 <- table(cellFromXY(x19, lat_lon_2018))

x19[as.numeric(names(tab19))] <- tab19

yearly_data
```


```{r}
df19 <- data.frame(coordinates(x19), count = x19[])
df19 <- df19 %>% 
  mutate(prop2018 = count/1075)  %>%
  dplyr::select(-count)
```

## 2019
```{r}
lat_lon_2019 <- joined_data %>%
  filter(year == "2019")

coordinates(lat_lon_2019) = c("lon", "lat")

x20 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x20[] <- 0

tab20 <- table(cellFromXY(x20, lat_lon_2019))

x20[as.numeric(names(tab20))] <- tab20

yearly_data
```


```{r}
df20 <- data.frame(coordinates(x20), count = x20[])
df20 <- df20 %>% 
  mutate(prop2019 = count/459)  %>%
  dplyr::select(-count)
df20
```


## 2020
```{r}
lat_lon_2020 <- joined_data %>%
  filter(year == "2020")

coordinates(lat_lon_2020) = c("lon", "lat")

x21 <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.6, 
            crs = "+proj=longlat +datum=WGS84")

x21[] <- 0

tab21 <- table(cellFromXY(x21, lat_lon_2020))

x21[as.numeric(names(tab21))] <- tab21

yearly_data
```


```{r}
df21 <- data.frame(coordinates(x21), count = x21[])
df21 <- df21 %>% 
  mutate(prop2020 = count/563)  %>%
  dplyr::select(-count)
df21
```


# joining all
```{r}
df1
```


```{r}
df_joined <- left_join(df1,df2, by = c("x", "y"))

#df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, by = c("x", "y"))
df_joined <- left_join(df_joined, df3, by = c("x", "y"))
df_joined <- left_join(df_joined, df4, by = c("x", "y"))
df_joined <- left_join(df_joined, df5, by = c("x", "y"))
df_joined <- left_join(df_joined, df6, by = c("x", "y"))
df_joined <- left_join(df_joined, df7, by = c("x", "y"))
df_joined <- left_join(df_joined, df8, by = c("x", "y"))
df_joined <- left_join(df_joined, df9, by = c("x", "y"))
df_joined <- left_join(df_joined, df10, by = c("x", "y"))
df_joined <- left_join(df_joined, df11, by = c("x", "y"))
df_joined <- left_join(df_joined, df12, by = c("x", "y"))
df_joined <- left_join(df_joined, df13, by = c("x", "y"))
df_joined <- left_join(df_joined, df14, by = c("x", "y"))
df_joined <- left_join(df_joined, df15, by = c("x", "y"))
df_joined <- left_join(df_joined, df16, by = c("x", "y"))
df_joined <- left_join(df_joined, df17, by = c("x", "y"))
df_joined <- left_join(df_joined, df18, by = c("x", "y"))
df_joined <- left_join(df_joined, df19, by = c("x", "y"))
df_joined <- left_join(df_joined, df20, by = c("x", "y"))
df_joined <- left_join(df_joined, df21, by = c("x", "y"))
df_joined
```

```{r}
library(tidyr)
df_long <- df_joined %>%
  pivot_longer(3:23, names_to = "year", values_to = "values")

#coordinates(df_long) <- c("x", "y")
#df_joined
```

```{r}
df_long
```

### for the training data
```{r}
df_training <- df_joined %>%
  dplyr::select(-prop2019, -prop2020) %>%
  pivot_longer(3:21, names_to = "year", values_to = "values")
df_training_mean <- df_training %>%
  group_by(x, y) %>%
  summarise(mean_training = mean(values))

df_training_mean$id <- 1:120
```


### for the hotspot data
```{r}
df_hotspot <- df_joined %>%
  dplyr::select(x, y, prop2019, prop2020) %>%
  pivot_longer(3:4, names_to = "year", values_to = "values")
df_hotspot_mean <- df_hotspot %>%
  group_by(x, y) %>%
  summarise(mean_hotspot = mean(values))
df_hotspot_mean
```
```{r}
df_hotspot_mean$id <- 1:120
```

## creating a dotplot to check the difference between the hotspot data and the training data
```{r}
df_training_mean %>%
  left_join(df_hotspot_mean, by = "id") %>%
  rename(lon = x.x,
         lat = y.x) %>%
  dplyr::select(-x.y, -y.y) %>%
  group_by(lon, lat) %>%
  ggplot(aes(x = mean_training,
             y = mean_hotspot,
             label = id)) +
  geom_text()
ggplotly()
```
some cells have different proportions where some are high for the hotspot and low for training, and otherwise.



```{r}
library(ggthemes)
library(rnaturalearth)
au_map <- ne_states(country = 'Australia', returnclass = 'sf')
vic_map <- au_map[7,]
df_long %>%
  ggplot() +
  geom_sf(data = vic_map, fill = "white") +
  geom_point(aes(x, y, col = values), size = 1) +
  theme_map(base_size = 10) +
  theme(legend.position = "none") +
  facet_wrap(~year, nrow = 4)
  
```









```{r}
df_joined <- df_joined %>%
  dplyr::select(-x, -y) %>%
  mutate(id = 1:120)
df_joined

```





# using the gridRecords function
```{r}
gridRecords <- function(rst,
                        pres.coords,
                        abs.coords = NULL,
                        na.rm = TRUE) {
  
  # version 2.0 (3 Feb 2020)
  
  if (!requireNamespace("raster")) stop("This function requires installing the 'raster' package first.")
  
  if (is.null(abs.coords)) {
    abs.coords <- raster::coordinates(rst)
  }

  p_extract <- raster::extract(rst, pres.coords, cellnumbers = TRUE, df = TRUE)[ , -1]
  a_extract <- raster::extract(rst, abs.coords, cellnumbers = TRUE, df = TRUE)[ , -1]
  
  p_extract <- unique(p_extract)
  a_extract <- unique(a_extract)
  
  a_extract <- a_extract[!(a_extract$cells %in% p_extract$cells), ]
  
  p_centroids <- raster::xyFromCell(rst, p_extract$cells)
  a_centroids <- raster::xyFromCell(rst, a_extract$cells)
  
  p_extract <- data.frame(presence = 1, p_centroids, p_extract)
  if (nrow(a_extract) > 0) {
    a_extract <- data.frame(presence = 0, a_centroids, a_extract)
  }
  
  result <- rbind(p_extract, a_extract)
  
  if (na.rm) {
    result_NA <- which(apply(result[ , 5:ncol(result)], MARGIN = 1, FUN = function(x) all(is.na(x))))
    if (length(result_NA) > 0) {
      result <- result[-result_NA, ]
    }
  }
  
  return(result)
}
```

```{r}
# set up projection parameter for use throughout script
projection <- "+proj=longlat +datum=WGS84"

# set up extent parameter 
ext <- extent(141, 150, -39, -34)

x <- raster(xmn = 141,
            xmx = 150, 
            ymn = -39,
            ymx = -34,
            res = 0.2, 
            crs = "+proj=longlat +datum=WGS84")

fire_data <- rasterize(joined_data[, c('lon', 'lat')], x, joined_data[, c('arf360')])

fire_projected <- projectRaster(fire_data, crs = projection)

fire_extended <- extend(fire_projected_jan, ext, value = NA)

plot(fire_extended)

set.seed(2021)
presences <- sp::spsample(as(ext, "SpatialPolygons"), 50, type = "random")
absences <- sp::spsample(as(ext, "SpatialPolygons"), 50, type = "random")
points(presences, pch = 20, cex = 0.2, col = "black")
points(absences, pch = 20, cex = 0.2, col = "white")

# you can also do it with only presence (no absence) records:
gridded_pres <- gridRecords(fire_extended, coordinates(presences))
head(gridded_pres)
plot(rst[[1]])
points(presences, pch = 20, cex = 0.2, col = "black")
pres_coords <- gridded_pres[gridded_pres$presence == 1, c("x", "y")]
abs_coords <- gridded_pres[gridded_pres$presence == 0, c("x", "y")]
points(gridded_pres[ , c("x", "y")], pch = 4, cex = 0.6, col = gridded_pres$presence)
```





```{r}
r <- setValues(vic_raster, sample(x = 0:1, size = ncell(vic_raster), replace = T))

plot(r)
```

```{r}
joined_data_raster <- joined_data %>%
  
```

```{r}

```




```{r}
# aggregate raster object to create a new RasterLayer with a lower resolution (larger cells)
r_agg <- aggregate(x = r, fact = 50, fun = sum)
```











```{r}
values(vic_raster_crop)
```


```{r}
name <- levels(vic_raster_crop)
head(name[[1]])
colnames(
